#include <iostream.h>
#include <conio.h>

main () {
  //deklarasei konstanta
  const float phi=3.14;
  const int r1=3;
  const float r2=10.7;
  const char kar='A';
  const char teks[30]="Contoh deklarasi konstanta" ;
  const bool n=true;

  //pemanggilan konstanta
  cout<<teks<<"\n";
  cout<<kar<<"\n";
  cout<<n<<"\n";
  cout<<phi<<"\n";
  cout<<r1<<"\n";
  cout<<r2<<"\n";
getch();}
  

